name: ACR Build Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment Type'
        type: environment
        required: true

jobs:
  docker_build:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: development
  
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Create Datetime Tag
      run: echo "NOW=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
    
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Export Telegraf
      uses: docker/build-push-action@v5
      with:
        push: false
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/telegraf:master-${{ env.NOW }}
        file: scripts/ci.docker
        outputs: type=oci,dest=/tmp/telegraf-image.tar

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: telegraf-image
        path: /tmp/telegraf-image.tar
  
  dev_publish:
    name: 'Push to Dev ACR'
    runs-on: ubuntu-latest
    environment: 'development'
    permissions:
      contents: none
    needs: docker_build

    steps:
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
        with:
          name: telegraf-image
          path: /tmp
      
      - name: Load Docker image
        run: |
          docker load --input /tmp/telegraf-image.tar
          docker image ls -a

      - name: Push to Dev ACR
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/telegraf:master-${{ env.NOW }}
          file: scripts/ci.docker

  prod_publish:
    name: 'Push to Prod ACR'
    runs-on: ubuntu-latest
    environment: 'production'
    permissions:
      contents: none
    needs: dev_publish

    steps:
      - name: Download artifacts (Docker images) from previous workflows
        uses: actions/download-artifact@v2
        with:
          name: telegraf-image
          path: /tmp
      
      - name: Load Docker image
        run: |
          docker load --input /tmp/telegraf-image.tar
          docker image ls -a

      - name: Push to Prod ACR
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/telegraf:master-${{ env.NOW }}
          file: scripts/ci.docker
